# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cardetails',
            fields=[
                ('carid', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('caryear', models.IntegerField(db_column='CarYear')),
                ('carnum', models.IntegerField(db_column='CarNum')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('jalbumlink', models.CharField(blank=True, db_column='JAlbumLink', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CarDetails',
            },
        ),
        migrations.CreateModel(
            name='Cardetailsupdate',
            fields=[
                ('updateid', models.CharField(db_column='UpdateId', max_length=10, primary_key=True, serialize=False)),
                ('caryear', models.IntegerField(blank=True, db_column='CarYear', null=True)),
                ('carnum', models.IntegerField(blank=True, db_column='CarNum', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('jalbumlink', models.CharField(blank=True, db_column='JAlbumLink', max_length=100, null=True)),
                ('carid', models.ForeignKey(db_column='CarID', on_delete=django.db.models.deletion.CASCADE, to='EB.Cardetails')),
            ],
            options={
                'db_table': 'CarDetailsUpdate',
            },
        ),
        migrations.CreateModel(
            name='Carimages',
            fields=[
                ('carcategory', models.CharField(db_column='CarCategory', max_length=30)),
                ('caryear', models.IntegerField(db_column='CarYear')),
                ('carnum', models.IntegerField(db_column='CarNum')),
                ('imagenum', models.IntegerField(db_column='ImageNum', primary_key=True, serialize=False)),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
            ],
            options={
                'db_table': 'CarImages',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapterid', models.IntegerField(db_column='ChapterID', primary_key=True, serialize=False)),
                ('chaptername', models.CharField(blank=True, db_column='ChapterName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=150, null=True)),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=150, null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=150, null=True)),
                ('superchapterid', models.ForeignKey(db_column='SuperChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters')),
            ],
            options={
                'db_table': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='HistoricalImages',
            fields=[
                ('imageurl', models.CharField(db_column='ImageUrl', max_length=100)),
                ('imagecaption', models.CharField(blank=True, db_column='ImageCaption', max_length=200, null=True)),
                ('imageid', models.AutoField(db_column='ImageID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Historical_Images',
            },
        ),
        migrations.CreateModel(
            name='Historicalinformation',
            fields=[
                ('sectionid', models.CharField(db_column='SectionID', max_length=50, primary_key=True, serialize=False)),
                ('sectionorder', models.IntegerField(db_column='SectionOrder')),
                ('sectiontitle', models.CharField(blank=True, db_column='SectionTitle', max_length=50, null=True)),
                ('sectiontext', models.TextField(blank=True, db_column='SectionText', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('chapterid', models.ForeignKey(db_column='ChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters')),
            ],
            options={
                'db_table': 'HistoricalInformation',
            },
        ),
        migrations.AddField(
            model_name='historicalimages',
            name='sectionid',
            field=models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.CASCADE, to='EB.Historicalinformation'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='chapterid',
            field=models.ForeignKey(db_column='ChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters'),
        ),
    ]
