# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetails',
            options={'ordering': ['caryear', 'carnum']},
        ),
        migrations.AddField(
            model_name='cardetails',
            name='status',
            field=models.CharField(blank=True, db_column='CarStatus', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='carid',
            field=models.CharField(db_column='id', max_length=30, primary_key=True, serialize=False),
        ),
    ]
