# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-29 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB', '0002_auto_20161210_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardetailspending',
            fields=[
                ('carid', models.CharField(db_column='id', max_length=30, primary_key=True, serialize=False)),
                ('caryear', models.IntegerField(db_column='CarYear')),
                ('carnum', models.IntegerField(db_column='CarNum')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('jalbumlink', models.CharField(blank=True, db_column='JAlbumLink', max_length=100, null=True)),
                ('status', models.CharField(blank=True, db_column='CarStatus', max_length=30, null=True)),
                ('chapterid', models.CharField(blank=True, db_column='ChapterID', max_length=50, null=True)),
                ('approved', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0, validators=[django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'ordering': ['caryear', 'carnum'],
                'db_table': 'CarDetailsPending',
            },
        ),
    ]
