"""
Django settings for itp_clc project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd)bw-e&*if9ob$kt1ahrglz479$%x3k&9!!!v-zwx$jqhp)rbu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EB',
    'EL',
    'V16',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itp_clc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#PREPEND_WWW = True
#SECURE_HSTS_SECONDS = ???
#SECURE_CONTENT_TYPE_NOSNIFF = True
#SECURE_BROWSER_XSS_FILTER = True
#SECURE_SSL_REDIRECT = True
##SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
#CSRF_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

WSGI_APPLICATION = 'itp_clc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'newcadillac',
        'USER':'mycadillac',
        'PASSWORD':'database123%',
        'HOST':'127.0.0.1',
        'PORT':'3306'
    },
    'EL': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'EL_newcadillac',
         'USER':'mycadillac',
         'PASSWORD':'database123%',
         'HOST':'127.0.0.1',
         'PORT':'3306'
     },
    'V16': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'V16_newcadillac',
         'USER':'mycadillac',
         'PASSWORD':'database123%',
         'HOST':'127.0.0.1',
         'PORT':'3306'
      },             
}

# URL of the login page.
LOGIN_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_HOST_USER = 'mrcadillac@newcadillacdatabase.org'
EMAIL_HOST_PASSWORD = 'Claude1960%'
DEFAULT_FROM_EMAIL = 'mrcadillac@newcadillacdatabase.org'
SERVER_EMAIL = 'mrcadillac@newcadillacdatabase.org'
EMAIL_PORT = 80 
EMAIL_USE_TLS = False

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, "static"),
    'C:/users/admin/workspace/itp_clc/static/',
]

#STATIC_ROOT = 'C:/users/admin/workspace/itp_clc/static/'
STATIC_URL = '/static/'

DATABASE_ROUTERS = ['EL.routers.DatabaseAppsRouter', 'V16.routers.DatabaseAppsRouter']

if DEBUG:
    # will output to your console
    logging.basicConfig(
        level = logging.DEBUG,
        format = '%(asctime)s %(levelname)s %(message)s',
    )